name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and test
      run: xcodebuild clean test -project swift-challenges.xcodeproj -scheme "swift-challengesTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
